### ISSUE TITLE
Stable 1.0.0 release - checklist

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#38]
I think there are some things needed before we make stable 1.0.0 release __updated__:

- [x] [0.4.0 release items (milestone 1)](https://github.com/xmldom/xmldom/milestone/1), including test coverage (#35) and cleaner module exports (#36)
- [x] [0.5.0 release item(s) - (milestone 3)](https://github.com/xmldom/xmldom/milestone/3), including some more general code cleanup
- [ ] ensure that all [1.0.0 release items in milestone 4](https://github.com/xmldom/xmldom/milestone/4) are completed
- [ ] ensure that we do not need any more major changes for 3-6 months or so

(raised in response to discussion in PR #28)

**Comment by karfau** [comment]
Instead of maintaining check lists in an issue we are now using milestones, so I'll close this one.
